using B2B.Objects.Entities.Masterdata;

namespace B2B;

public static class Countries
{
    public static Country[] All =>
    [
        new Country { Id = "",   Name = "UNKNOWN", InEuropeanUnion = false },
        new Country { Id = "AF", Name = "AFGHANISTAN", InEuropeanUnion = false },
        new Country { Id = "AX", Name = "ÅLAND ISLANDS", InEuropeanUnion = false },
        new Country { Id = "AL", Name = "ALBANIA", InEuropeanUnion = false },
        new Country { Id = "DZ", Name = "ALGERIA", InEuropeanUnion = false },
        new Country { Id = "AS", Name = "AMERICAN SAMOA", InEuropeanUnion = false },
        new Country { Id = "AD", Name = "ANDORRA", InEuropeanUnion = false },
        new Country { Id = "AO", Name = "ANGOLA", InEuropeanUnion = false },
        new Country { Id = "AI", Name = "ANGUILLA", InEuropeanUnion = false },
        new Country { Id = "AQ", Name = "ANTARCTICA", InEuropeanUnion = false },
        new Country { Id = "AG", Name = "ANTIGUA AND BARBUDA", InEuropeanUnion = false },
        new Country { Id = "AR", Name = "ARGENTINA", InEuropeanUnion = false },
        new Country { Id = "AM", Name = "ARMENIA", InEuropeanUnion = false },
        new Country { Id = "AW", Name = "ARUBA", InEuropeanUnion = false },
        new Country { Id = "AU", Name = "AUSTRALIA", InEuropeanUnion = false },
        new Country { Id = "AT", Name = "AUSTRIA", InEuropeanUnion = true },
        new Country { Id = "AZ", Name = "AZERBAIJAN", InEuropeanUnion = false },
        new Country { Id = "BS", Name = "BAHAMAS", InEuropeanUnion = false },
        new Country { Id = "BH", Name = "BAHRAIN", InEuropeanUnion = false },
        new Country { Id = "BD", Name = "BANGLADESH", InEuropeanUnion = false },
        new Country { Id = "BB", Name = "BARBADOS", InEuropeanUnion = false },
        new Country { Id = "BY", Name = "BELARUS", InEuropeanUnion = false },
        new Country { Id = "BE", Name = "BELGIUM", InEuropeanUnion = false },
        new Country { Id = "BZ", Name = "BELIZE", InEuropeanUnion = false },
        new Country { Id = "BJ", Name = "BENIN", InEuropeanUnion = false },
        new Country { Id = "BM", Name = "BERMUDA", InEuropeanUnion = false },
        new Country { Id = "BT", Name = "BHUTAN", InEuropeanUnion = false },
        new Country { Id = "BO", Name = "BOLIVIA", InEuropeanUnion = false },
        new Country { Id = "BA", Name = "BOSNIA AND HERZEGOVINA", InEuropeanUnion = false },
        new Country { Id = "BW", Name = "BOTSWANA", InEuropeanUnion = false },
        new Country { Id = "BV", Name = "BOUVET ISLAND", InEuropeanUnion = false },
        new Country { Id = "BR", Name = "BRAZIL", InEuropeanUnion = false },
        new Country { Id = "IO", Name = "BRITISH INDIAN OCEAN TERRITORY", InEuropeanUnion = false },
        new Country { Id = "BN", Name = "BRUNEI DARUSSALAM", InEuropeanUnion = false },
        new Country { Id = "BG", Name = "BULGARIA", InEuropeanUnion = true },
        new Country { Id = "BF", Name = "BURKINA FASO", InEuropeanUnion = true },
        new Country { Id = "BI", Name = "BURUNDI", InEuropeanUnion = false },
        new Country { Id = "KH", Name = "CAMBODIA", InEuropeanUnion = false },
        new Country { Id = "CM", Name = "CAMEROON", InEuropeanUnion = false },
        new Country { Id = "CA", Name = "CANADA", InEuropeanUnion = false },
        new Country { Id = "CV", Name = "CAPE VERDE", InEuropeanUnion = false },
        new Country { Id = "KY", Name = "CAYMAN ISLANDS", InEuropeanUnion = false },
        new Country { Id = "CF", Name = "CENTRAL AFRICAN REPUBLIC", InEuropeanUnion = false },
        new Country { Id = "TD", Name = "CHAD", InEuropeanUnion = false },
        new Country { Id = "CL", Name = "CHILE", InEuropeanUnion = false },
        new Country { Id = "CN", Name = "CHINA", InEuropeanUnion = false },
        new Country { Id = "CX", Name = "CHRISTMAS ISLAND", InEuropeanUnion = false },
        new Country { Id = "CC", Name = "COCOS (KEELING) ISLANDS", InEuropeanUnion = false },
        new Country { Id = "CO", Name = "COLOMBIA", InEuropeanUnion = false },
        new Country { Id = "KM", Name = "COMOROS", InEuropeanUnion = false },
        new Country { Id = "CG", Name = "CONGO", InEuropeanUnion = false },
        new Country { Id = "CD", Name = "CONGO, DEMOCRATIC REPUBLIC OF", InEuropeanUnion = false },
        new Country { Id = "CK", Name = "COOK ISLANDS", InEuropeanUnion = false },
        new Country { Id = "CR", Name = "COSTA RICA", InEuropeanUnion = false },
        new Country { Id = "CI", Name = "COTE D'IVOIRE", InEuropeanUnion = false },
        new Country { Id = "HR", Name = "CROATIA", InEuropeanUnion = false },
        new Country { Id = "CU", Name = "CUBA", InEuropeanUnion = false },
        new Country { Id = "CY", Name = "CYPRUS", InEuropeanUnion = true },
        new Country { Id = "CZ", Name = "CZECH REPUBLIC", InEuropeanUnion = true },
        new Country { Id = "DK", Name = "DENMARK", InEuropeanUnion = true },
        new Country { Id = "DJ", Name = "DJIBOUTI", InEuropeanUnion = false },
        new Country { Id = "DM", Name = "DOMINICA", InEuropeanUnion = false },
        new Country { Id = "DO", Name = "DOMINICAN REPUBLIC", InEuropeanUnion = false },
        new Country { Id = "EC", Name = "ECUADOR", InEuropeanUnion = false },
        new Country { Id = "EG", Name = "EGYPT", InEuropeanUnion = false },
        new Country { Id = "SV", Name = "EL SALVADOR", InEuropeanUnion = false },
        new Country { Id = "GQ", Name = "EQUATORIAL GUINEA", InEuropeanUnion = false },
        new Country { Id = "ER", Name = "ERITREA", InEuropeanUnion = false },
        new Country { Id = "EE", Name = "ESTONIA", InEuropeanUnion = true },
        new Country { Id = "ET", Name = "ETHIOPIA", InEuropeanUnion = false },
        new Country { Id = "FK", Name = "FALKLAND ISLANDS (MALVINAS)", InEuropeanUnion = false },
        new Country { Id = "FO", Name = "FAROE ISLANDS", InEuropeanUnion = false },
        new Country { Id = "FJ", Name = "FIJI", InEuropeanUnion = false },
        new Country { Id = "FI", Name = "FINLAND", InEuropeanUnion = true },
        new Country { Id = "FR", Name = "FRANCE", InEuropeanUnion = true },
        new Country { Id = "GF", Name = "FRENCH GUIANA", InEuropeanUnion = false },
        new Country { Id = "PF", Name = "FRENCH POLYNESIA", InEuropeanUnion = false },
        new Country { Id = "TF", Name = "FRENCH SOUTHERN TERRITORIES", InEuropeanUnion = false },
        new Country { Id = "GA", Name = "GABON", InEuropeanUnion = false },
        new Country { Id = "GM", Name = "GAMBIA", InEuropeanUnion = false },
        new Country { Id = "GE", Name = "GEORGIA", InEuropeanUnion = false },
        new Country { Id = "GG", Name = "GUERNSEY", InEuropeanUnion = false },
        new Country { Id = "JE", Name = "JERSEY", InEuropeanUnion = false },
        new Country { Id = "IM", Name = "ISLE OF MAN", InEuropeanUnion = false },
        new Country { Id = "DE", Name = "GERMANY", InEuropeanUnion = true },
        new Country { Id = "GH", Name = "GHANA", InEuropeanUnion = false },
        new Country { Id = "GI", Name = "GIBRALTAR", InEuropeanUnion = false },
        new Country { Id = "GR", Name = "GREECE", InEuropeanUnion = true },
        new Country { Id = "GL", Name = "GREENLAND", InEuropeanUnion = false },
        new Country { Id = "GD", Name = "GRENADA", InEuropeanUnion = false },
        new Country { Id = "GP", Name = "GUADELOUPE", InEuropeanUnion = false },
        new Country { Id = "GU", Name = "GUAM", InEuropeanUnion = false },
        new Country { Id = "GT", Name = "GUATEMALA", InEuropeanUnion = false },
        new Country { Id = "GN", Name = "GUINEA", InEuropeanUnion = false },
        new Country { Id = "GW", Name = "GUINEA-BISSAU", InEuropeanUnion = false },
        new Country { Id = "GY", Name = "GUYANA", InEuropeanUnion = false },
        new Country { Id = "HT", Name = "HAITI", InEuropeanUnion = false },
        new Country { Id = "HM", Name = "HEARD ISLAND AND MCDONALD ISLANDS", InEuropeanUnion = false },
        new Country { Id = "VA", Name = "HOLY SEE (VATICAN CITY STATE) ", InEuropeanUnion = false },
        new Country { Id = "HN", Name = "HONDURAS", InEuropeanUnion = false },
        new Country { Id = "HK", Name = "HONG KONG", InEuropeanUnion = false },
        new Country { Id = "HU", Name = "HUNGARY", InEuropeanUnion = true },
        new Country { Id = "IS", Name = "ICELAND", InEuropeanUnion = false },
        new Country { Id = "IN", Name = "INDIA", InEuropeanUnion = false },
        new Country { Id = "ID", Name = "INDONESIA", InEuropeanUnion = false },
        new Country { Id = "IR", Name = "IRAN, ISLAMIC REPUBLIC OF", InEuropeanUnion = false },
        new Country { Id = "IQ", Name = "IRAQ", InEuropeanUnion = false },
        new Country { Id = "IE", Name = "IRELAND", InEuropeanUnion = true },
        new Country { Id = "IL", Name = "ISRAEL", InEuropeanUnion = false },
        new Country { Id = "IT", Name = "ITALY", InEuropeanUnion = true },
        new Country { Id = "JM", Name = "JAMAICA", InEuropeanUnion = false },
        new Country { Id = "JP", Name = "JAPAN", InEuropeanUnion = false },
        new Country { Id = "JO", Name = "JORDAN", InEuropeanUnion = false },
        new Country { Id = "KZ", Name = "KAZAKHSTAN", InEuropeanUnion = false },
        new Country { Id = "KE", Name = "KENYA", InEuropeanUnion = false },
        new Country { Id = "KI", Name = "KIRIBATI", InEuropeanUnion = false },
        new Country { Id = "KP", Name = "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", InEuropeanUnion = false },
        new Country { Id = "KR", Name = "KOREA, REPUBLIC OF", InEuropeanUnion = false },
        new Country { Id = "KW", Name = "KUWAIT", InEuropeanUnion = false },
        new Country { Id = "KG", Name = "KYRGYZSTAN", InEuropeanUnion = false },
        new Country { Id = "LA", Name = "LAO PEOPLE'S DEMOCRATIC REPUBLIC", InEuropeanUnion = false },
        new Country { Id = "LV", Name = "LATVIA", InEuropeanUnion = true },
        new Country { Id = "LB", Name = "LEBANON", InEuropeanUnion = false },
        new Country { Id = "LS", Name = "LESOTHO", InEuropeanUnion = false },
        new Country { Id = "LR", Name = "LIBERIA", InEuropeanUnion = false },
        new Country { Id = "LY", Name = "LIBYAN ARAB JAMAHIRIYA", InEuropeanUnion = false },
        new Country { Id = "LI", Name = "LIECHTENSTEIN", InEuropeanUnion = false },
        new Country { Id = "LT", Name = "LITHUANIA", InEuropeanUnion = true },
        new Country { Id = "LU", Name = "LUXEMBOURG", InEuropeanUnion = true },
        new Country { Id = "MO", Name = "MACAO", InEuropeanUnion = false },
        new Country { Id = "MK", Name = "MACEDONIA,FORMER YUGOSLAV REPUBLIC", InEuropeanUnion = false },
        new Country { Id = "MG", Name = "MADAGASCAR", InEuropeanUnion = false },
        new Country { Id = "MW", Name = "MALAWI", InEuropeanUnion = false },
        new Country { Id = "MY", Name = "MALAYSIA", InEuropeanUnion = false },
        new Country { Id = "MV", Name = "MALDIVES", InEuropeanUnion = false },
        new Country { Id = "ML", Name = "MALI", InEuropeanUnion = false },
        new Country { Id = "MT", Name = "MALTA", InEuropeanUnion = true },
        new Country { Id = "MH", Name = "MARSHALL ISLANDS", InEuropeanUnion = false },
        new Country { Id = "MQ", Name = "MARTINIQUE", InEuropeanUnion = false },
        new Country { Id = "MR", Name = "MAURITANIA", InEuropeanUnion = false },
        new Country { Id = "MU", Name = "MAURITIUS", InEuropeanUnion = false },
        new Country { Id = "YT", Name = "MAYOTTE", InEuropeanUnion = false },
        new Country { Id = "MX", Name = "MEXICO", InEuropeanUnion = false },
        new Country { Id = "FM", Name = "MICRONESIA, FEDERATED STATES OF", InEuropeanUnion = false },
        new Country { Id = "MD", Name = "MOLDOVA, REPUBLIC OF", InEuropeanUnion = false },
        new Country { Id = "MC", Name = "MONACO", InEuropeanUnion = false },
        new Country { Id = "ME", Name = "MONTENEGRO", InEuropeanUnion = false },
        new Country { Id = "MN", Name = "MONGOLIA", InEuropeanUnion = false },
        new Country { Id = "MS", Name = "MONTSERRAT", InEuropeanUnion = false },
        new Country { Id = "MA", Name = "MOROCCO", InEuropeanUnion = false },
        new Country { Id = "MZ", Name = "MOZAMBIQUE", InEuropeanUnion = false },
        new Country { Id = "MM", Name = "MYANMAR", InEuropeanUnion = false },
        new Country { Id = "NA", Name = "NAMIBIA", InEuropeanUnion = false },
        new Country { Id = "NR", Name = "NAURU", InEuropeanUnion = false },
        new Country { Id = "NP", Name = "NEPAL", InEuropeanUnion = false },
        new Country { Id = "NL", Name = "NETHERLANDS", InEuropeanUnion = true },
        new Country { Id = "AN", Name = "NETHERLANDS ANTILLES", InEuropeanUnion = false },
        new Country { Id = "NC", Name = "NEW CALEDONIA", InEuropeanUnion = false },
        new Country { Id = "NZ", Name = "NEW ZEALAND", InEuropeanUnion = false },
        new Country { Id = "NI", Name = "NICARAGUA", InEuropeanUnion = false },
        new Country { Id = "NE", Name = "NIGER", InEuropeanUnion = false },
        new Country { Id = "NG", Name = "NIGERIA", InEuropeanUnion = false },
        new Country { Id = "NU", Name = "NIUE", InEuropeanUnion = false },
        new Country { Id = "NF", Name = "NORFOLK ISLAND", InEuropeanUnion = false },
        new Country { Id = "MP", Name = "NORTHERN MARIANA ISLANDS", InEuropeanUnion = false },
        new Country { Id = "NO", Name = "NORWAY", InEuropeanUnion = false },
        new Country { Id = "OM", Name = "OMAN", InEuropeanUnion = false },
        new Country { Id = "PK", Name = "PAKISTAN", InEuropeanUnion = false },
        new Country { Id = "PW", Name = "PALAU", InEuropeanUnion = false },
        new Country { Id = "PS", Name = "PALESTINIAN TERRITORY, OCCUPIED", InEuropeanUnion = false },
        new Country { Id = "PA", Name = "PANAMA", InEuropeanUnion = false },
        new Country { Id = "PG", Name = "PAPUA NEW GUINEA", InEuropeanUnion = false },
        new Country { Id = "PY", Name = "PARAGUAY", InEuropeanUnion = false },
        new Country { Id = "PE", Name = "PERU", InEuropeanUnion = false },
        new Country { Id = "PH", Name = "PHILIPPINES", InEuropeanUnion = false },
        new Country { Id = "PN", Name = "PITCAIRN", InEuropeanUnion = false },
        new Country { Id = "PL", Name = "POLAND", InEuropeanUnion = true },
        new Country { Id = "PT", Name = "PORTUGAL", InEuropeanUnion = true },
        new Country { Id = "PR", Name = "PUERTO RICO", InEuropeanUnion = false },
        new Country { Id = "QA", Name = "QATAR", InEuropeanUnion = false },
        new Country { Id = "RE", Name = "REUNION", InEuropeanUnion = false },
        new Country { Id = "RO", Name = "ROMANIA", InEuropeanUnion = true },
        new Country { Id = "RU", Name = "RUSSIAN FEDERATION", InEuropeanUnion = false },
        new Country { Id = "RW", Name = "RWANDA", InEuropeanUnion = false },
        new Country { Id = "SH", Name = "SAINT HELENA", InEuropeanUnion = false },
        new Country { Id = "KN", Name = "SAINT KITTS AND NEVIS", InEuropeanUnion = false },
        new Country { Id = "LC", Name = "SAINT LUCIA", InEuropeanUnion = false },
        new Country { Id = "PM", Name = "SAINT PIERRE AND MIQUELON", InEuropeanUnion = false },
        new Country { Id = "VC", Name = "SAINT VINCENT AND THE GRENADINES", InEuropeanUnion = false },
        new Country { Id = "WS", Name = "SAMOA", InEuropeanUnion = false },
        new Country { Id = "SM", Name = "SAN MARINO", InEuropeanUnion = false },
        new Country { Id = "ST", Name = "SAO TOME AND PRINCIPE", InEuropeanUnion = false },
        new Country { Id = "SA", Name = "SAUDI ARABIA", InEuropeanUnion = false },
        new Country { Id = "SN", Name = "SENEGAL", InEuropeanUnion = false },
        new Country { Id = "CS", Name = "SERBIA AND MONTENEGRO", InEuropeanUnion = false },
        new Country { Id = "SC", Name = "SEYCHELLES", InEuropeanUnion = false },
        new Country { Id = "SL", Name = "SIERRA LEONE", InEuropeanUnion = false },
        new Country { Id = "SG", Name = "SINGAPORE", InEuropeanUnion = false },
        new Country { Id = "SK", Name = "SLOVAKIA", InEuropeanUnion = true },
        new Country { Id = "SI", Name = "SLOVENIA", InEuropeanUnion = true },
        new Country { Id = "SB", Name = "SOLOMON ISLANDS", InEuropeanUnion = false },
        new Country { Id = "SO", Name = "SOMALIA", InEuropeanUnion = false },
        new Country { Id = "ZA", Name = "SOUTH AFRICA", InEuropeanUnion = false },
        new Country { Id = "GS", Name = "SOUTH GEORGIA & SOUTH SANDWICH ISLANDS", InEuropeanUnion = false },
        new Country { Id = "ES", Name = "SPAIN", InEuropeanUnion = true },
        new Country { Id = "LK", Name = "SRI LANKA", InEuropeanUnion = false },
        new Country { Id = "SD", Name = "SUDAN", InEuropeanUnion = false },
        new Country { Id = "SR", Name = "SURINAME", InEuropeanUnion = false },
        new Country { Id = "SJ", Name = "SVALBARD AND JAN MAYEN", InEuropeanUnion = false },
        new Country { Id = "SZ", Name = "SWAZILAND", InEuropeanUnion = false },
        new Country { Id = "SE", Name = "SWEDEN", InEuropeanUnion = true },
        new Country { Id = "CH", Name = "SWITZERLAND", InEuropeanUnion = false },
        new Country { Id = "SY", Name = "SYRIAN ARAB REPUBLIC", InEuropeanUnion = false },
        new Country { Id = "TW", Name = "TAIWAN, PROVINCE OF CHINA", InEuropeanUnion = false },
        new Country { Id = "TJ", Name = "TAJIKISTAN", InEuropeanUnion = false },
        new Country { Id = "TZ", Name = "TANZANIA, UNITED REPUBLIC OF", InEuropeanUnion = false },
        new Country { Id = "TH", Name = "THAILAND", InEuropeanUnion = false },
        new Country { Id = "TL", Name = "TIMOR-LESTE", InEuropeanUnion = false },
        new Country { Id = "TG", Name = "TOGO", InEuropeanUnion = false },
        new Country { Id = "TK", Name = "TOKELAU", InEuropeanUnion = false },
        new Country { Id = "TO", Name = "TONGA", InEuropeanUnion = false },
        new Country { Id = "TT", Name = "TRINIDAD AND TOBAGO", InEuropeanUnion = false },
        new Country { Id = "TN", Name = "TUNISIA", InEuropeanUnion = false },
        new Country { Id = "TR", Name = "TURKEY", InEuropeanUnion = false },
        new Country { Id = "TM", Name = "TURKMENISTAN", InEuropeanUnion = false },
        new Country { Id = "TC", Name = "TURKS AND CAICOS ISLANDS", InEuropeanUnion = false },
        new Country { Id = "TV", Name = "TUVALU", InEuropeanUnion = false },
        new Country { Id = "UG", Name = "UGANDA", InEuropeanUnion = false },
        new Country { Id = "UA", Name = "UKRAINE", InEuropeanUnion = false },
        new Country { Id = "AE", Name = "UNITED ARAB EMIRATES", InEuropeanUnion = false },
        new Country { Id = "GB", Name = "UNITED KINGDOM", InEuropeanUnion = false },
        new Country { Id = "US", Name = "UNITED STATES", InEuropeanUnion = false },
        new Country { Id = "UM", Name = "UNITED STATES MINOR OUTLYING ISLANDS", InEuropeanUnion = false },
        new Country { Id = "UY", Name = "URUGUAY", InEuropeanUnion = false },
        new Country { Id = "UZ", Name = "UZBEKISTAN", InEuropeanUnion = false },
        new Country { Id = "VU", Name = "VANUATU", InEuropeanUnion = false },
        new Country { Id = "VE", Name = "VENEZUELA", InEuropeanUnion = false },
        new Country { Id = "VN", Name = "VIET NAM", InEuropeanUnion = false },
        new Country { Id = "VG", Name = "VIRGIN ISLANDS, BRITISH", InEuropeanUnion = false },
        new Country { Id = "VI", Name = "VIRGIN ISLANDS, U.S.", InEuropeanUnion = false },
        new Country { Id = "WF", Name = "WALLIS AND FUTUNA", InEuropeanUnion = false },
        new Country { Id = "EH", Name = "WESTERN SAHARA", InEuropeanUnion = false },
        new Country { Id = "YE", Name = "YEMEN", InEuropeanUnion = false },
        new Country { Id = "ZM", Name = "ZAMBIA", InEuropeanUnion = false },
        new Country { Id = "ZW", Name = "ZIMBABWE", InEuropeanUnion = false },
        new Country { Id = "RS", Name = "REPUBLIC OF SERBIA", InEuropeanUnion = false }
    ];
}