using B2B.Objects.Entities.Security;

namespace B2B.Data.EF
{
    public partial class B2BDbContext
    {
        private static B2BPrivilege[] Privileges => new B2BPrivilege[]
        {
            // Active transactions
            new B2BPrivilege { Id = "activetransaction_delete",                  PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "activetransaction_read",                    PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "activetransaction_create",                  PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "activetransaction_update",                  PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },

            new B2BPrivilege { Id = "address_create",                            PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "address_delete",                            PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "address_read",                              PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "address_update",                            PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
                                                                                                                                                          
            // Security                                                                                                                                   
            new B2BPrivilege { Id = "b2brole_create",                            PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "b2brole_delete",                            PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "b2brole_read",                              PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "b2brole_update",                            PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "b2buser_create",                            PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "b2buser_delete",                            PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "b2buser_read",                              PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "b2buser_update",                            PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "b2buserrole_create",                        PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "b2buserrole_delete",                        PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "b2buserrole_read",                          PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "b2buserrole_update",                        PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
                                                                                                                                  
            // Buckets                                                                                                            
            new B2BPrivilege { Id = "bucket_create",                             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucket_delete",                             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucket_read",                               PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "bucket_update",                             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketcompany_create",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketcompany_delete",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketcompany_read",                        PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "bucketcompany_update",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketcredit_create",                       PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketcredit_delete",                       PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketcredit_read",                         PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "bucketcredit_update",                       PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketinvoice_create",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketinvoice_delete",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketinvoice_read",                        PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "bucketinvoice_update",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketoffer_create",                        PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketoffer_delete",                        PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketoffer_read",                          PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "bucketoffer_update",                        PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketpurchaseorder_create",                PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketpurchaseorder_delete",                PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketpurchaseorder_read",                  PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "bucketpurchaseorder_update",                PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketremittanceadvice_create",             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketremittanceadvice_delete",             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketremittanceadvice_read",               PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "bucketremittanceadvice_update",             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketrole_create",                         PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketrole_delete",                         PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketrole_read",                           PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "bucketrole_update",                         PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketsystem_create",                       PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketsystem_delete",                       PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketsystem_read",                         PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "bucketsystem_update",                       PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },

            new B2BPrivilege { Id = "bucketoverview_create",                     PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketoverview_delete",                     PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "bucketoverview_read",                       PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "bucketoverview_update",                     PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },

            new B2BPrivilege { Id = "company_write",                             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "company_read",                              PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "companyreference_create",                   PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "companyreference_delete",                   PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "companyreference_read",                     PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "companyreference_update",                   PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "country_create",                            PortalAdminsOnly = true,  RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "country_delete",                            PortalAdminsOnly = true,  RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "country_read",                              PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "country_update",                            PortalAdminsOnly = true,  RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },

            // Credits
            new B2BPrivilege { Id = "credit_create",                             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credit_creditorarchive",                    PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "credit_creditorcomplete",                   PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "credit_creditorpropose",                    PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "credit_creditorreceive",                    PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "credit_creditorrejectorcancel",             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "credit_creditorsend",                       PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "credit_creditorsendforfunding",             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "credit_debtorapprove",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credit_debtorarchive",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credit_debtorcomplete",                     PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credit_debtorhold",                         PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credit_debtorpay",                          PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credit_debtorpropose",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credit_debtorreceive",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credit_debtorrejectorcancel",               PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credit_debtorsend",                         PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credit_debtorsendforfunding",               PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credit_delete",                             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credit_funderarchive",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "credit_fundercomplete",                     PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "credit_funderpay",                          PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "credit_funderpropose",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "credit_funderreceive",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "credit_funderrejectorcancel",               PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "credit_fundersend",                         PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "credit_read",                               PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "credit_update",                             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "creditaudititem_create",                    PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "creditaudititem_delete",                    PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "creditaudititem_read",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "creditaudititem_update",                    PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "creditcompany_create",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "creditcompany_delete",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "creditcompany_read",                        PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "creditcompany_update",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "creditline_create",                         PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "creditline_delete",                         PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "creditline_read",                           PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "creditline_update",                         PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "creditreference_create",                    PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "creditreference_delete",                    PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "creditreference_read",                      PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "creditreference_update",                    PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credittype_create",                         PortalAdminsOnly = true,  RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credittype_delete",                         PortalAdminsOnly = true,  RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "credittype_read",                           PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "credittype_update",                         PortalAdminsOnly = true,  RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },

            new B2BPrivilege { Id = "currency_create",                           PortalAdminsOnly = true,  RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "currency_delete",                           PortalAdminsOnly = true,  RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "currency_read",                             PortalAdminsOnly = false, RootAdminPriv = true,  BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "currency_update",                           PortalAdminsOnly = true,  RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },

            new B2BPrivilege { Id = "fundingdetail_create",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "fundingdetail_delete",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "fundingdetail_read",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "fundingdetail_update",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },

            // Invoices
            new B2BPrivilege { Id = "invoice_create",                            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_creditorarchive",                   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "invoice_creditorcomplete",                  PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "invoice_creditorpropose",                   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "invoice_creditorreceive",                   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "invoice_creditorrejectorcancel",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "invoice_creditorsend",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "invoice_creditorsendforfunding",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_debtorapprove",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_debtorarchive",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_debtorcomplete",                    PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_debtorhold",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_debtorpay",                         PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_debtorpropose",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_debtorreceive",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_debtorrejectorcancel",              PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_debtorsend",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_debtorsendforfunding",              PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_delete",                            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoice_funderarchive",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "invoice_fundercomplete",                    PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "invoice_funderpay",                         PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "invoice_funderpropose",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "invoice_funderreceive",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "invoice_funderrejectorcancel",              PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "invoice_fundersend",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "invoice_read",                              PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "invoice_update",                            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoiceaudititem_create",                   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoiceaudititem_delete",                   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoiceaudititem_read",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "invoiceaudititem_update",                   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoicecompany_create",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoicecompany_delete",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoicecompany_read",                       PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "invoicecompany_update",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoiceline_create",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoiceline_delete",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoiceline_read",                          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "invoiceline_update",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoicereference_create",                   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoicereference_delete",                   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoicereference_read",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "invoicereference_update",                   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoicetype_create",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoicetype_delete",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "invoicetype_read",                          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "invoicetype_update",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },

            // Offers
            new B2BPrivilege { Id = "offer_create",                              PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offer_creditoraccept",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "offer_creditorarchive",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "offer_creditorcomplete",                    PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "offer_creditorfundingaccept",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "offer_creditorpropose",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "offer_creditorreceive",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "offer_creditorrejectorcancel",              PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "offer_creditorsend",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "offer_debtoraccept",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "offer_debtorarchive",                       PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "offer_debtorcomplete",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "offer_debtorfundingaccept",                 PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "offer_debtorpay",                           PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "offer_debtorpropose",                       PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "offer_debtorreceive",                       PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "offer_debtorrejectorcancel",                PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "offer_debtorsend",                          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "offer_delete",                              PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offer_funderaccept",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offer_funderarchive",                       PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offer_fundercomplete",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offer_funderfundingaccept",                 PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offer_funderpay",                           PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offer_funderpropose",                       PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "offer_funderreceive",                       PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "offer_funderrejectorcancel",                PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "offer_fundersend",                          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offer_propose",                             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offer_read",                                PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "offer_update",                              PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offeraudititem_create",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "offeraudititem_delete",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "offeraudititem_read",                       PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "offeraudititem_update",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "offercompany_create",                       PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offercompany_delete",                       PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offercompany_read",                         PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "offercompany_update",                       PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offerdataitem_create",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offerdataitem_delete",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offerdataitem_read",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "offerdataitem_update",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offerline_create",                          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offerline_delete",                          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offerline_read",                            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "offerline_update",                          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offerreference_create",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offerreference_delete",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "offerreference_read",                       PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "offerreference_update",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },

            // Purchase Orders
            new B2BPrivilege { Id = "purchaseorder_create",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_creditorapprove",             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_creditorarchive",             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_creditorcomplete",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_creditorhold",                PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_creditorpropose",             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_creditorreceive",             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_creditorrejectorcancel",      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_creditorsend",                PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_debtorarchive",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_debtorcomplete",              PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_debtorpropose",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_debtorreceive",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_debtorrejectorcancel",        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_debtorsend",                  PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_delete",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorder_funderarchive",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "purchaseorder_fundercomplete",              PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "purchaseorder_funderpropose",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "purchaseorder_funderreceive",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "purchaseorder_funderrejectorcancel",        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "purchaseorder_fundersend",                  PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "purchaseorder_read",                        PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "purchaseorder_update",                      PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorderaudititem_create",             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorderaudititem_delete",             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorderaudititem_read",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "purchaseorderaudititem_update",             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseordercompany_create",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseordercompany_delete",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseordercompany_read",                 PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "purchaseordercompany_update",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorderline_create",                  PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorderline_delete",                  PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorderline_read",                    PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "purchaseorderline_update",                  PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorderreference_create",             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorderreference_delete",             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "purchaseorderreference_read",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "purchaseorderreference_update",             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true,  BuyerPriv = false, SupplierPriv = false, FunderPriv = false },

            // Payments
            new B2BPrivilege { Id = "remittanceadvice_create",                   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_creditorarchive",          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_creditorcomplete",         PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_creditorpropose",          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_creditorreceive",          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_creditorrejectorcancel",   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_creditorsend",             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = true,  FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_debtorarchive",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_debtorcomplete",           PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_debtorpropose",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_debtorreceive",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_debtorrejectorcancel",     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_debtorsend",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_delete",                   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvice_funderarchive",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "remittanceadvice_fundercomplete",           PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "remittanceadvice_funderpropose",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "remittanceadvice_funderreceive",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "remittanceadvice_funderrejectorcancel",     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "remittanceadvice_fundersend",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = true  },
            new B2BPrivilege { Id = "remittanceadvice_read",                     PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "remittanceadvice_update",                   PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadviceaudititem_create",          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadviceaudititem_delete",          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadviceaudititem_read",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "remittanceadviceaudititem_update",          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvicecompany_create",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvicecompany_delete",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvicecompany_read",              PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "remittanceadvicecompany_update",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadviceline_create",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadviceline_delete",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadviceline_read",                 PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "remittanceadviceline_update",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvicereference_create",          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvicereference_delete",          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvicereference_read",            PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "remittanceadvicereference_update",          PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvicetype_create",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvicetype_delete",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "remittanceadvicetype_read",                 PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "remittanceadvicetype_update",               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },

            // Rates.
            new B2BPrivilege { Id = "rate_create",                               PortalAdminsOnly = true, RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "rate_read",                                 PortalAdminsOnly = true, RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "rate_update",                               PortalAdminsOnly = true, RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "rate_delete",                               PortalAdminsOnly = true, RootAdminPriv = false, BuyerAdminPriv = false, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },

            // Systems.
            new B2BPrivilege { Id = "system_create",                             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "system_delete",                             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },
            new B2BPrivilege { Id = "system_read",                               PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = true,  SupplierPriv = true,  FunderPriv = true  },
            new B2BPrivilege { Id = "system_update",                             PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false },


            new B2BPrivilege { Id = "import",                                    PortalAdminsOnly = false, RootAdminPriv = true, BuyerAdminPriv = true, BuyerPriv = false, SupplierPriv = false, FunderPriv = false }
        };
    }
}